language: python
python:
- 3.9.1
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database jobquest_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: QLkV8IlGz4OcXVgYNwBjQ2RCfmrA9rwtr5jpVzhmojdTzem6XIMVf4SJ1eWmGOsPB0Q1OsCqb52MPrzpqo0dRZ6EFC0bnXWmX+nmvy4Fh4eS4F8qOUBdpMg1moT8nFMvzQcLi6tJ+hL6nMdJ6Zx4kuN+VQM/2peVdW//AGpCWRYwoC+TPh91WAB7ts9H/ob0feoUMeUWxnU7GzJ7mOy0g8W3GMbF1q0pjpCv2DmsFz7eZlaq4F28T2uswhuq1D3pfjMH4m6hk+4X0yW8Ze6QaSbh5YRmRG5KGgJd+MFBbIvXSqukUEDM6uyqb99lXRzVfMumcsPKYd/YlD4m3uPKCfzP5tcYOlXHTv3vM+Lu8/oHZN01Lj1fSwhsq4RBZybf7XYCQ3REL7mtbv8Wt4Wy4BjCC/XqRHOf1RCCM3e0A+cFVkInk7Iy6iDR5ZD1BJmzJ1A9kfdmYxRqz6K7kXGwZ0M0TDKF5AVwhUSSkpWvSwMoZcw1VSwgTSFPF3YaBnCfNWKBKYctpCub9d1MBhOQVNVqfCZp1Aqe1tCxVgQgMk8p0EuXJQtE+62uy6SAp6clgSp0TSf+hMKBb83hGyd0njPSFs2SO6u/AsCoIGhEZ412guYSrs/WCQijgWES1dVfXhY/D44eGhsFQOVVv6mc+4m0bpc4ZTZ0KdwwURF1ejg=
  app: job-quest-be
  on:
    repo: JobQuest/jobquest-be
    branch: main
  skip_cleanup: 'true'
  run:
  - pip install -r requirements.txt
  - python manage.py db upgrade
