dist: xenial
language: python
python:
- '3.9.1'
services:
- postgresql
addons:
  postgresql: '13'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'drop database jobquest_test;' -U postgres
- psql -c 'create database jobquest_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure:
  app: job-quest-be
  on:
    repo: JobQuest/jobquest-be
    branch: main
  skip_cleanup: 'true'
  run:
    - pip install -r requirements.txt
    - python manage.py db upgrade
