"""empty message

Revision ID: 4dd54aaf872c
Revises: bbe5117c266e
Create Date: 2021-02-22 12:08:31.215147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd54aaf872c'
down_revision = 'bbe5117c266e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('progress', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'progress')
    # ### end Alembic commands ###
