"""empty message

Revision ID: 5991db2cb3de
Revises: ecd3daacfda2
Create Date: 2021-02-20 19:20:09.549933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5991db2cb3de'
down_revision = 'ecd3daacfda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('quest_type', sa.String(length=80), nullable=False),
    sa.Column('monster_image', sa.String(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounters')
    # ### end Alembic commands ###
