"""empty message

Revision ID: 6f2bd39b7fb7
Revises: ad5b16b26c1c
Create Date: 2021-02-21 17:28:03.626731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2bd39b7fb7'
down_revision = 'ad5b16b26c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_quests_quest_id'), 'user_quests', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_quests_user_id'), 'user_quests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_quests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_quests', 'quests', ['quest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_quests', type_='foreignkey')
    op.drop_constraint(None, 'user_quests', type_='foreignkey')
    op.drop_index(op.f('ix_user_quests_user_id'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_quest_id'), table_name='user_quests')
    # ### end Alembic commands ###
