"""empty message

Revision ID: 84d69f92ad00
Revises: 8fc8634bd663
Create Date: 2021-02-22 11:40:24.973846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d69f92ad00'
down_revision = '8fc8634bd663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actions_encounter_id', table_name='actions')
    op.drop_column('actions', 'type')
    op.drop_column('actions', 'title')
    op.drop_index('ix_encounters_quest_id', table_name='encounters')
    op.drop_column('encounters', 'type')
    op.drop_column('encounters', 'description')
    op.add_column('quests', sa.Column('level', sa.Integer(), nullable=False))
    op.drop_index('ix_user_quests_quest_id', table_name='user_quests')
    op.drop_index('ix_user_quests_user_id', table_name='user_quests')
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.create_index('ix_user_quests_user_id', 'user_quests', ['user_id'], unique=False)
    op.create_index('ix_user_quests_quest_id', 'user_quests', ['quest_id'], unique=False)
    op.drop_column('quests', 'level')
    op.add_column('encounters', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('encounters', sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_index('ix_encounters_quest_id', 'encounters', ['quest_id'], unique=False)
    op.add_column('actions', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('actions', sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_index('ix_actions_encounter_id', 'actions', ['encounter_id'], unique=False)
    # ### end Alembic commands ###
