"""empty message

Revision ID: 9e0ddf753e43
Revises: 4dd54aaf872c
Create Date: 2021-02-22 16:23:25.544501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e0ddf753e43'
down_revision = '4dd54aaf872c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('actions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_actions_timestamp', table_name='actions')
    op.drop_column('actions', 'timestamp')
    op.add_column('encounters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('encounters', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_encounters_timestamp', table_name='encounters')
    op.drop_column('encounters', 'timestamp')
    op.add_column('quests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('quests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_quests_timestamp', table_name='quests')
    op.drop_column('quests', 'timestamp')
    op.add_column('user_quests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_quests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_quests_quest_id', table_name='user_quests')
    op.drop_index('ix_user_quests_timestamp', table_name='user_quests')
    op.drop_index('ix_user_quests_user_id', table_name='user_quests')
    op.drop_column('user_quests', 'timestamp')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_timestamp', table_name='users')
    op.drop_column('users', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_users_timestamp', 'users', ['timestamp'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('user_quests', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_user_quests_user_id', 'user_quests', ['user_id'], unique=False)
    op.create_index('ix_user_quests_timestamp', 'user_quests', ['timestamp'], unique=False)
    op.create_index('ix_user_quests_quest_id', 'user_quests', ['quest_id'], unique=False)
    op.drop_column('user_quests', 'updated_at')
    op.drop_column('user_quests', 'created_at')
    op.add_column('quests', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_quests_timestamp', 'quests', ['timestamp'], unique=False)
    op.drop_column('quests', 'updated_at')
    op.drop_column('quests', 'created_at')
    op.add_column('encounters', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_encounters_timestamp', 'encounters', ['timestamp'], unique=False)
    op.drop_column('encounters', 'updated_at')
    op.drop_column('encounters', 'created_at')
    op.add_column('actions', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_actions_timestamp', 'actions', ['timestamp'], unique=False)
    op.drop_column('actions', 'updated_at')
    op.drop_column('actions', 'created_at')
    # ### end Alembic commands ###
