"""empty message

Revision ID: bbe5117c266e
Revises: 84d69f92ad00
Create Date: 2021-02-22 11:52:54.910059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe5117c266e'
down_revision = '84d69f92ad00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actions_encounter_id'), 'actions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_encounters_quest_id'), 'encounters', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_quests_quest_id'), 'user_quests', ['quest_id'], unique=False)
    op.create_index(op.f('ix_user_quests_user_id'), 'user_quests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quests_user_id'), table_name='user_quests')
    op.drop_index(op.f('ix_user_quests_quest_id'), table_name='user_quests')
    op.drop_index(op.f('ix_encounters_quest_id'), table_name='encounters')
    op.drop_index(op.f('ix_actions_encounter_id'), table_name='actions')
    # ### end Alembic commands ###
