"""empty message

Revision ID: ecd3daacfda2
Revises: ce37a698bbec
Create Date: 2021-02-20 18:46:40.231131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd3daacfda2'
down_revision = 'ce37a698bbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False, foreign_key='quest.id'),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='user.id'),
    sa.Column('completion_status', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quests')
    # ### end Alembic commands ###
