"""empty message

Revision ID: f1f02b72493c
Revises: 10fec2670ba2
Create Date: 2021-02-20 20:12:46.033271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f02b72493c'
down_revision = '10fec2670ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('type', sa.String(length=80), nullable=False))
    op.drop_column('encounters', 'quest_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('quest_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('encounters', 'type')
    # ### end Alembic commands ###
